export const plan = {
  page: {
    metaTitle: "Your study plan",
    title: "Lernplan",
    description:
      "A week-by-week plan to your exam date. It puts your weakest parts first, schedules mock exams for the last weeks and ticks tasks off automatically when you complete them.",
  },
  examDate: "Exam date",
  perDay: "Time per day",
  /** Follows the bold number of days. */
  daysLeft: (n: number): string => (n === 1 ? "day left" : "days left"),
  weeks: (n: number) => (n === 1 ? "1 week" : `${n} weeks`),
  pastDate: "Your exam date is in the past.",
  noDate: "No exam date set – showing an 8-week plan.",
  week: (n: number) => `Week ${n}`,
  thisWeek: "This week",
  tasks: (n: number) => (n === 1 ? "1 task" : `${n} tasks`),
  done: (n: number) => `${n} done`,
  /** Texts generated by the plan builder (src/lib/plan/build-plan.ts). */
  builder: {
    phases: {
      foundations: {
        name: "Foundations",
        focus: "Refresh core grammar and vocabulary and get to know every part of the exam.",
      },
      training: {
        name: "Exam training",
        focus: "Practise every part under exam timing and concentrate on your weakest parts.",
      },
      mocks: {
        name: "Mock exams",
        focus: "Full mock exams under real conditions, targeted work on remaining gaps.",
      },
      final: {
        name: "Final week",
        focus: "Light review, Redemittel, strategies – and rest before the exam.",
      },
    },
    grammar: (title: string) => `Grammar · ${title}`,
    grammarDetail: "explanation + drills",
    vocab: (title: string) => `Vocabulary · ${title}`,
    vocabDetail: "add to flashcards, quiz",
    mockDetail: (minutes: number) => `full written exam · ${minutes} min`,
    review: "Mistake trainer",
    reviewDetail: "10 min on 3 days",
    strategies: "Read the strategies for every part",
    strategiesDetail: "and the exam-day tips",
    phrases: "Revise Redemittel for Schreiben and Sprechen",
    phrasesDetail: "say them aloud",
  },
};
