import type { ExamDefinition } from "./types";

/**
 * telc Deutsch B1 (Zertifikat Deutsch), format of the revised 2019 edition.
 * Source: telc Übungstest 1 – item counts, points, timing and rubrics.
 */
export const telcB1: ExamDefinition = {
  id: "telc-b1",
  slug: "telc-b1",
  name: "telc Deutsch B1",
  alias: "Zertifikat Deutsch",
  level: "B1",
  description:
    "The most widely taken B1 certificate in Germany – accepted for citizenship, permanent residence, jobs and university preparation.",
  written: { maxPoints: 225, passPoints: 135, minutes: 150 },
  oral: { maxPoints: 75, passPoints: 45, minutes: 15, prepMinutes: 20 },
  totalPoints: 300,
  grades: [
    { min: 270, label: "sehr gut", labelEn: "very good" },
    { min: 240, label: "gut", labelEn: "good" },
    { min: 210, label: "befriedigend", labelEn: "satisfactory" },
    { min: 180, label: "ausreichend", labelEn: "sufficient" },
    { min: 0, label: "nicht bestanden", labelEn: "not passed" },
  ],
  sections: [
    {
      id: "lesen",
      name: "Leseverstehen",
      short: "Lesen",
      nameEn: "Reading",
      description: "Three reading tasks: gist, detail and scanning for specific information.",
      maxPoints: 75,
      minutes: 90,
      timeNote: "Lesen and Sprachbausteine share one 90-minute block.",
      parts: [
        {
          id: "lesen-1",
          sectionId: "lesen",
          slug: "teil-1",
          teil: 1,
          name: "Globalverstehen",
          nameEn: "Reading for gist",
          setType: "headline-matching",
          items: 5,
          firstItem: 1,
          pointsPerItem: 5,
          maxPoints: 25,
          minutes: 15,
          instruction:
            "Lesen Sie die Überschriften a–j und die Texte 1–5. Finden Sie für jeden Text die passende Überschrift. Sie können jede Überschrift nur einmal benutzen.",
          instructionEn:
            "Read headlines a–j and texts 1–5. Find the matching headline for each text. Each headline can be used only once.",
          description:
            "Five short press texts and ten headlines. You must grasp the main message of each text – five headlines are traps that reuse the same words.",
        },
        {
          id: "lesen-2",
          sectionId: "lesen",
          slug: "teil-2",
          teil: 2,
          name: "Detailverstehen",
          nameEn: "Reading for detail",
          setType: "text-mc",
          items: 5,
          firstItem: 6,
          pointsPerItem: 5,
          maxPoints: 25,
          minutes: 20,
          instruction: "Lesen Sie den Text und die Aufgaben 6–10. Welche Lösung (a, b oder c) ist jeweils richtig?",
          instructionEn: "Read the text and tasks 6–10. Which answer (a, b or c) is correct?",
          description:
            "One longer newspaper or magazine article with five multiple-choice questions that follow the order of the text.",
        },
        {
          id: "lesen-3",
          sectionId: "lesen",
          slug: "teil-3",
          teil: 3,
          name: "Selektives Verstehen",
          nameEn: "Scanning",
          setType: "ad-matching",
          items: 10,
          firstItem: 11,
          pointsPerItem: 2.5,
          maxPoints: 25,
          minutes: 20,
          instruction:
            "Lesen Sie die Situationen 11–20 und die Anzeigen a–l. Finden Sie für jede Situation die passende Anzeige. Sie können jede Anzeige nur einmal benutzen. Wenn Sie zu einer Situation keine Anzeige finden, markieren Sie ein x.",
          instructionEn:
            "Read situations 11–20 and ads a–l. Find the matching ad for each situation. Each ad can be used only once. If no ad fits a situation, mark x.",
          description:
            "Ten everyday situations and twelve classified ads. Scan for the decisive detail – and spot the situations for which no ad fits.",
        },
      ],
    },
    {
      id: "sprachbausteine",
      name: "Sprachbausteine",
      short: "Sprachbausteine",
      nameEn: "Language elements",
      description: "Grammar and vocabulary in context: two gap-fill letters.",
      maxPoints: 30,
      minutes: 90,
      timeNote: "Shares the 90-minute block with Leseverstehen.",
      parts: [
        {
          id: "sprachbausteine-1",
          sectionId: "sprachbausteine",
          slug: "teil-1",
          teil: 1,
          name: "Grammatik",
          nameEn: "Grammar",
          setType: "gap-mc",
          items: 10,
          firstItem: 21,
          pointsPerItem: 1.5,
          maxPoints: 15,
          minutes: 15,
          instruction:
            "Lesen Sie den Text und schließen Sie die Lücken 21–30. Welche Lösung (a, b oder c) ist jeweils richtig?",
          instructionEn: "Read the text and fill gaps 21–30. Which answer (a, b or c) is correct?",
          description:
            "A letter or e-mail with ten gaps. Each gap tests a grammar point: endings, prepositions, connectors, verb forms, pronouns.",
        },
        {
          id: "sprachbausteine-2",
          sectionId: "sprachbausteine",
          slug: "teil-2",
          teil: 2,
          name: "Lexik",
          nameEn: "Vocabulary",
          setType: "gap-wordbank",
          items: 10,
          firstItem: 31,
          pointsPerItem: 1.5,
          maxPoints: 15,
          minutes: 15,
          instruction:
            "Lesen Sie den Text und schließen Sie die Lücken 31–40. Benutzen Sie die Wörter a–o. Jedes Wort passt nur einmal.",
          instructionEn: "Read the text and fill gaps 31–40 using words a–o. Each word fits only once.",
          description:
            "A text with ten gaps and fifteen words. Five words are left over – collocations and fixed prepositions decide.",
        },
      ],
    },
    {
      id: "hoeren",
      name: "Hörverstehen",
      short: "Hören",
      nameEn: "Listening",
      description: "Radio surveys, an interview and everyday announcements – richtig oder falsch.",
      maxPoints: 75,
      minutes: 30,
      timeNote: "The recording runs without interruption in the real exam.",
      parts: [
        {
          id: "hoeren-1",
          sectionId: "hoeren",
          slug: "teil-1",
          teil: 1,
          name: "Globalverstehen",
          nameEn: "Listening for gist",
          setType: "audio-short",
          items: 5,
          firstItem: 41,
          pointsPerItem: 5,
          maxPoints: 25,
          minutes: 6,
          instruction:
            "Sie hören nun fünf kurze Texte. Dazu sollen Sie fünf Aufgaben lösen. Sie hören diese Texte nur einmal. Entscheiden Sie beim Hören, ob die Aussagen 41–45 richtig oder falsch sind. Lesen Sie jetzt die Aufgaben 41–45. Sie haben dazu 30 Sekunden Zeit.",
          instructionEn:
            "You will hear five short texts and solve five tasks. You hear the texts ONLY ONCE. Decide while listening whether statements 41–45 are true or false. You have 30 seconds to read them first.",
          description:
            "Five people give their opinion on one topic (like a radio street survey). Heard only once – you need the speaker's overall view.",
          audio: {
            plays: 1,
            readingSeconds: 30,
            repeatPauseSeconds: 0,
            itemPauseSeconds: 6,
            answerSeconds: 15,
            perItem: false,
          },
        },
        {
          id: "hoeren-2",
          sectionId: "hoeren",
          slug: "teil-2",
          teil: 2,
          name: "Detailverstehen",
          nameEn: "Listening for detail",
          setType: "audio-long",
          items: 10,
          firstItem: 46,
          pointsPerItem: 2.5,
          maxPoints: 25,
          minutes: 12,
          instruction:
            "Sie hören nun ein Gespräch. Dazu sollen Sie zehn Aufgaben lösen. Sie hören das Gespräch zweimal. Entscheiden Sie beim Hören, ob die Aussagen 46–55 richtig oder falsch sind. Lesen Sie jetzt die Aufgaben 46–55. Sie haben dazu eine Minute Zeit.",
          instructionEn:
            "You will hear a conversation and solve ten tasks. You hear it TWICE. Decide while listening whether statements 46–55 are true or false. You have one minute to read them first.",
          description:
            "A radio interview or conversation of about four minutes. Ten statements follow the order of the recording.",
          audio: {
            plays: 2,
            readingSeconds: 60,
            repeatPauseSeconds: 20,
            itemPauseSeconds: 0,
            answerSeconds: 30,
            perItem: false,
          },
        },
        {
          id: "hoeren-3",
          sectionId: "hoeren",
          slug: "teil-3",
          teil: 3,
          name: "Selektives Verstehen",
          nameEn: "Listening for specific information",
          setType: "audio-short",
          items: 5,
          firstItem: 56,
          pointsPerItem: 5,
          maxPoints: 25,
          minutes: 8,
          instruction:
            "Sie hören nun fünf kurze Texte. Dazu sollen Sie fünf Aufgaben lösen. Sie hören jeden Text zweimal. Entscheiden Sie beim Hören, ob die Aussagen 56–60 richtig oder falsch sind.",
          instructionEn:
            "You will hear five short texts and solve five tasks. You hear EACH text TWICE. Decide while listening whether statements 56–60 are true or false.",
          description:
            "Announcements, voicemails, radio tips and weather reports. Listen for one precise detail: a time, a place, a price, an instruction.",
          audio: {
            plays: 2,
            readingSeconds: 10,
            repeatPauseSeconds: 5,
            itemPauseSeconds: 8,
            answerSeconds: 10,
            perItem: true,
          },
        },
      ],
    },
    {
      id: "schreiben",
      name: "Schriftlicher Ausdruck",
      short: "Schreiben",
      nameEn: "Writing",
      description: "One informal or semi-formal e-mail covering four guiding points.",
      maxPoints: 45,
      minutes: 30,
      parts: [
        {
          id: "schreiben",
          sectionId: "schreiben",
          slug: "aufgabe",
          teil: 1,
          name: "E-Mail",
          nameEn: "E-mail",
          setType: "writing-email",
          items: 0,
          firstItem: 0,
          pointsPerItem: 0,
          maxPoints: 45,
          minutes: 30,
          instruction:
            "Antworten Sie auf die E-Mail. Schreiben Sie etwas zu allen vier Punkten. Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, Einleitung und einen passenden Schluss.",
          instructionEn:
            "Reply to the e-mail and write something about all four points. Before writing, think about a sensible order, a subject line, a salutation, an introduction and a closing.",
          description:
            "Rated on task completion (the 4 Leitpunkte), communicative design (structure, connectors, register) and accuracy.",
        },
      ],
    },
    {
      id: "sprechen",
      name: "Mündlicher Ausdruck",
      short: "Sprechen",
      nameEn: "Speaking",
      description: "A paired conversation in three parts after 20 minutes of preparation.",
      maxPoints: 75,
      minutes: 15,
      timeNote: "Plus 20 minutes of preparation time with notes.",
      parts: [
        {
          id: "sprechen-1",
          sectionId: "sprechen",
          slug: "teil-1",
          teil: 1,
          name: "Einander kennenlernen",
          nameEn: "Getting to know each other",
          setType: "speaking-intro",
          items: 0,
          firstItem: 0,
          pointsPerItem: 0,
          maxPoints: 15,
          minutes: 3,
          instruction: "Unterhalten Sie sich mit Ihrer Partnerin bzw. Ihrem Partner über folgende Themen:",
          instructionEn: "Talk with your partner about the following topics:",
          description: "Introduce yourself and ask your partner questions – a natural, two-way conversation.",
          speaking: { minutes: 3, monologueSeconds: 90 },
        },
        {
          id: "sprechen-2",
          sectionId: "sprechen",
          slug: "teil-2",
          teil: 2,
          name: "Über ein Thema sprechen",
          nameEn: "Talking about a topic",
          setType: "speaking-topic",
          items: 0,
          firstItem: 0,
          pointsPerItem: 0,
          maxPoints: 30,
          minutes: 6,
          instruction:
            "Berichten Sie Ihrer Gesprächspartnerin bzw. Ihrem Gesprächspartner über die Meinung auf Ihrem Blatt. Unterhalten Sie sich dann über das Thema. Sagen Sie Ihre Meinung und erzählen Sie von eigenen Erfahrungen.",
          instructionEn:
            "Report the opinion on your sheet to your partner, then discuss the topic: give your opinion and talk about your own experiences.",
          description:
            "Each candidate has a different opinion card on the same topic. Present it, then discuss, compare and share experiences.",
          speaking: { minutes: 6, monologueSeconds: 75 },
        },
        {
          id: "sprechen-3",
          sectionId: "sprechen",
          slug: "teil-3",
          teil: 3,
          name: "Gemeinsam etwas planen",
          nameEn: "Planning something together",
          setType: "speaking-planning",
          items: 0,
          firstItem: 0,
          pointsPerItem: 0,
          maxPoints: 30,
          minutes: 6,
          instruction:
            "Planen Sie gemeinsam. Machen Sie Vorschläge, begründen Sie sie und reagieren Sie auf die Vorschläge Ihrer Partnerin bzw. Ihres Partners. Einigen Sie sich, was zu tun ist und wer welche Aufgabe übernimmt.",
          instructionEn:
            "Plan together: make and justify suggestions, react to your partner's ideas, and agree on what needs to be done and who does what.",
          description:
            "Organise an event or trip with your partner using a checklist. Suggesting, agreeing, objecting politely and reaching a decision are assessed.",
          speaking: { minutes: 6 },
        },
      ],
    },
  ],
  writingRubric: {
    multiplier: 3,
    maxPoints: 45,
    criteria: [
      {
        id: "I",
        name: "Aufgabenbewältigung",
        nameEn: "Task completion",
        assesses: ["Are all four guiding points (Leitpunkte) dealt with appropriately?"],
        bands: [
          { grade: "A", points: 5, descriptor: "All four guiding points are dealt with appropriately." },
          { grade: "B", points: 3, descriptor: "Three guiding points are dealt with appropriately." },
          { grade: "C", points: 1, descriptor: "Two guiding points are dealt with appropriately." },
          { grade: "D", points: 0, descriptor: "Only one or none of the guiding points is dealt with." },
        ],
      },
      {
        id: "II",
        name: "Kommunikative Gestaltung",
        nameEn: "Communicative design",
        assesses: [
          "Logical order of the guiding points",
          "Linking of sentences (connectors, references)",
          "Register and expression suited to the reader",
          "Text-type features: salutation, introduction, closing, sign-off",
        ],
        bands: [
          { grade: "A", points: 5, descriptor: "Upper B1: wide range of common phrases, clearly linked, consistent register." },
          { grade: "B", points: 3, descriptor: "B1: sufficient range; short elements linked into a connected text." },
          { grade: "C", points: 1, descriptor: "A2: basic phrases, simple connectors (und, aber, weil) only." },
          { grade: "D", points: 0, descriptor: "A1 or below: isolated words and formulas." },
        ],
      },
      {
        id: "III",
        name: "Formale Richtigkeit",
        nameEn: "Accuracy",
        assesses: ["Grammar (syntax, morphology)", "Spelling and punctuation", "Errors weighed by how much they hinder understanding"],
        bands: [
          { grade: "A", points: 5, descriptor: "Good control; occasional systematic errors, meaning always clear." },
          { grade: "B", points: 3, descriptor: "Adequate control; systematic errors, meaning mostly clear." },
          { grade: "C", points: 1, descriptor: "Simple structures correct, but elementary errors (tenses, agreement)." },
          { grade: "D", points: 0, descriptor: "Very limited control; text only partly understandable." },
        ],
      },
    ],
    notes: [
      "A guiding point counts if it is addressed meaningfully – even in one short sentence, or combined with another point in one sentence.",
      "Off-topic texts receive D in every criterion. A wrong situation (e.g. writing an invitation instead of accepting one) only sets criterion I to D.",
      "No A in criterion II if salutation/closing are missing, the register is wrong or mixed (du/Sie), points are listed without links, or most sentences start with “Ich”/“Wir”.",
      "Comprehensibility first: ending and gender errors weigh less than errors in verb agreement or word order.",
    ],
  },
  speakingRubric: {
    maxPoints: 75,
    criteria: [
      {
        id: "ausdruck",
        name: "Ausdrucksfähigkeit",
        nameEn: "Range of expression",
        assesses: ["Expression appropriate to content and role", "Vocabulary", "Realising your communicative intention"],
        descriptors: {
          A: "fully appropriate",
          B: "appropriate on the whole",
          C: "barely acceptable",
          D: "consistently insufficient",
        },
      },
      {
        id: "aufgabe",
        name: "Aufgabenbewältigung",
        nameEn: "Task management",
        assesses: ["Taking part in the conversation", "Discourse and compensation strategies", "Fluency"],
        descriptors: {
          A: "fully appropriate",
          B: "appropriate on the whole",
          C: "barely acceptable",
          D: "consistently insufficient",
        },
      },
      {
        id: "richtigkeit",
        name: "Formale Richtigkeit",
        nameEn: "Accuracy",
        assesses: ["Syntax and morphology"],
        descriptors: {
          A: "no or only isolated errors",
          B: "errors that do not impair understanding",
          C: "errors in key places that seriously impair understanding",
          D: "so many errors that communication breaks down",
        },
      },
      {
        id: "aussprache",
        name: "Aussprache und Intonation",
        nameEn: "Pronunciation & intonation",
        assesses: ["Deviations in pronunciation and intonation"],
        descriptors: {
          A: "do not impair understanding",
          B: "occasionally make understanding difficult",
          C: "make understanding considerably difficult",
          D: "make understanding (almost) impossible",
        },
      },
    ],
    points: {
      "sprechen-1": {
        ausdruck: { A: 4, B: 3, C: 1, D: 0 },
        aufgabe: { A: 4, B: 3, C: 1, D: 0 },
        richtigkeit: { A: 4, B: 3, C: 1, D: 0 },
        aussprache: { A: 3, B: 2, C: 1, D: 0 },
      },
      "sprechen-2": {
        ausdruck: { A: 8, B: 6, C: 2, D: 0 },
        aufgabe: { A: 8, B: 6, C: 2, D: 0 },
        richtigkeit: { A: 8, B: 6, C: 2, D: 0 },
        aussprache: { A: 6, B: 4, C: 2, D: 0 },
      },
      "sprechen-3": {
        ausdruck: { A: 8, B: 6, C: 2, D: 0 },
        aufgabe: { A: 8, B: 6, C: 2, D: 0 },
        richtigkeit: { A: 8, B: 6, C: 2, D: 0 },
        aussprache: { A: 6, B: 4, C: 2, D: 0 },
      },
    },
  },
};
